### ISSUE TITLE
Does not work with phantomjs 2.0

### ISSUE THREAD

**Issue by bchartoff** [kevinschaul/depict#15]
There's a current (recent) bug in phantomjs 2.0 on OSX
https://github.com/alexscheelmeyer/node-phantom/issues/115

For now, I just installed old version of phantomjs:
```
brew install homebrew/versions/phantomjs198
```

**Comment by mhkeller** [comment]
Check out this fix: https://github.com/ajam/banquo/pull/3

**Comment by mhkeller** [comment]
I see you might have already implemented this one https://github.com/kevinschaul/depict/commit/f57c183f47347e2400fcf3deaf6f3da91377ca4d

**Comment by kevinschaul** [comment]
Ah, you're right, that could fix it. Hopefully I'll have a chance to try soon.
